import subprocess

subprocess.run(["python", "progs/sprint1.py"])
subprocess.run(["python", "progs/sprint2.py"])
subprocess.run(["python", "progs/sprint3.py"])
subprocess.run(["python", "progs/sprint4.py"])
subprocess.run(["python", "progs/sprint5.py"])
subprocess.run(["python", "progs/sprint6.py"])
subprocess.run(["python", "progs/sprint7.py"])
subprocess.run(["python", "progs/sprint8.py"])
subprocess.run(["python", "progs/sprint9.py"])
subprocess.run(["python", "progs/sprint10.py"])
subprocess.run(["python", "progs/sprint11.py"])
subprocess.run(["python", "progs/sprint12.py"])
subprocess.run(["python", "progs/sprint13.py"])